### ISSUE TITLE
.sav files not getting synced

### ISSUE THREAD

**Issue by Zackyist** [ridgekuhn/arklone-retropie#1]
This seems like such a great utility and just what I've been looking for! However, it seems like Arklone only syncs _.srm_ files and not _.sav_ files, is this correct?

I have two save files, one _.srm_, one .sav, in the same folder and only the _.srm_ gets downloaded to my RetroPie device. On the Raspberry Pi Zero *gpSP* seems to be the default GBA emulator and it only saves in _.sav_. It would be great to get support for those files as well!

**Comment by ridgekuhn** [comment]
@Zackyist Oops, sorry, I guess I forgot about .sav. Luckily that's a very easy fix and I just took care of it. Pull from the latest master branch to get this commit: https://github.com/ridgekuhn/arklone-retropie/commit/8b0c450eaa611ce9118e152cffe09c04e1b1111e
